class Config:
    SECRET_KEY = '9483ky'
    SQLALCHEMY_DATABASE_URI = 'mysql+mysqlconnector://root:9483ky@localhost/indian_railway'
    SQLALCHEMY_TRACK_MODIFICATIONS = False


# WHILE IMPORTING FROM GITHUB YOU HAVE TO MAKE THE CONNECTION OF THIS FRONTEND TO THE DATABASE  i.e IN MYSQL MAKE THE DATABASE AND REQUIRED TABLE SAMW TO SAME AS IN THE MYSQL IMAGE, WITH SAME NAMES.
